### ISSUE TITLE
Published version of Google Sheets/Docs not updating

### ISSUE THREAD

**Issue by tpmccallum** [GoogleWebComponents/google-sheets#11]
Hi,
This is probably more of a browser cache issue but I would like to find a way to ensure that changes made to my sheet are reflected in the web page (web component).

Google Sheet:
I find that the published version of my sheet (or doc for that matter) are not reflecting the edit version of my sheet (when refreshing the published version of the sheet; works properly upon creation of a sheet).

Web Component:
I am seeing a similar thing happen in the web component and wonder if we can add some javascript (inside the web component) to force a refetch of content from the published version of the sheet.

Thanks a bunch you guys,
Chat soon
Tim

**Comment by ebidel** [comment]
Closing as this is old.

**Comment by sujay1848** [comment]
Hi,
I currently am going through the same problem.
I have a dashboard created in Google Sheets and it contains multiple charts.
I chose to publish it to web, while generating the link to embed only the sheet containing the dashboard, and publishing all content to web.
The dashboard is dynamic, since it consumes data from a Google Form.
When I submit a new response, the actual sheet gets updated instantly, all fine and dandy, but when I go to the sheet embedded in my web page, it still shows stale data.

Stopping publishing and republishing is not an option for me.

Does the "**Automatically republish when changes are made**." checkbox mean nothing?

Any solutions\responses are welcome.

Thanks,
Sujay

**Comment by sharon13m** [comment]
I'm having the same issue. :-/  My published Google Doc is not updated.  I tried to stop publishing and republish and it is not updating.

**Comment by ghost** [comment]
I am also facing the same issues. I had tried Stop Publishing and then Republish the sheet. But the front end is not taking the updated result. Any help will be appreciated.

**Comment by joaomantovani** [comment]
Same problem here +1

**Comment by briandodson** [comment]
Facing same issue +1

**Comment by acotton-ipd** [comment]
same

**Comment by KissBalazs** [comment]
Same problem here. Even If I use embedding plugins, or reading data from public urls, the changes only appears in 4-6 minutes after being made.

**Comment by steynvil** [comment]
Yes, that is correct, published charts in Google Sheets only update 5 minutes after a change was made. 

Here's a different but very simple approach to make a chart update instantly: https://medium.com/@steynviljoen/how-to-share-or-embed-a-google-sheets-chart-that-updates-instantly-no-need-to-wait-for-5-minutes-b6d325cd8598

**Comment by hd86xl** [comment]
@steynvil I reviewed your article, but my chart URL does not contain the "edit#" and my chart is its own sheet so I was not able to make your instructions work.

**Comment by ncabello0335** [comment]
Hi, i am having the same problem, in my case, when I open the google sheet  public url with a  guest user (in chrome browser) I do see the updated sheet, but  when i use my regular user it shows a previous version of the sheet

**Comment by JikuToken** [comment]
Im having the same issue.
